spring:
  application:
    name: FinancialServices-PROD
server:
  port: 8060
service:
  collateral:
    host: localhost
    port: 8070
  product:
    host: localhost
    port: 8080
  user:
    host: localhost
    port: 8090