product:
  management:
    message: Product Management PROD Properties file
    build-version: 2023.01.27
    mailDetails:
      host: test-product-management@fincorp.com
      port: 9000
      from: test-product-management@fincorp.com

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9040/eureka/

info:
  app:
    name: Product Management PROD
    description: Product Management PROD - A Finance Corporation Microservices
    version: 2023.01.27

management:
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
endpoints:
  shutdown:
    enabled: true